# -*- coding: utf-8 -*-
"""Lab1_P1_CamposGallegos_CristianKalid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HI7WLR5qrhRTtkur-8EJ9Xofe-mBPgt

# Lab 1. Creating a Class, Object, Attributes & Methods
## Student: Cristian Kalid Campos Gallegos
## Object Oriented Programming 4ºB TI BIS

In this lab you are going to explore and create a program that defines a class called "Keyboard".
"""

class Keyboard:
  def __init__(self, size, brand, layout):
    #self: se utiliza para decirle  a python que objeto pertenecen los atributos
    self.size = size
    self.brand = brand
    self.layout = layout

  def type(self):
    print("The keyboard is typing")

  def mayus(self):
    print("The keyboard is in BloqMayus Mode")

  def desc(self):
    print(f"Size: {self.size} "
          f"Brand: {self.brand} "
          f"Layout: {self.layout}")

## Create an instance using the class "table"
keyboard_1 = Keyboard("100%","Logitech","Spanish (Latin America)")
keyboard_2 = Keyboard("60%","Ryzen","US")

# We access to the object(Instance) "Table 1" to call its data
print(keyboard_1.size)
print(keyboard_2.brand)
keyboard_1.type()
keyboard_2.desc()

"""# Lab 1: Bank Account Class
Create a Python program that models a bank account using Object-Oriented Programming.
"""

# @title
class BankAccount:
  def __init__(self, holders_name, __balance):
    self.holders_name = holders_name
    self.balance = __balance

  def deposit(self):
    money_r = int(input("Insert the money to deposit:"))
    if money_r > 0:
      self.balance += money_r
      print(f"Actual balance: {self.balance}")
    else: print("ERROR: the value to deposit is to small")

  def withdraw(self):
    money_w = int(input("Insert the money to withdraw: "))
    if money_w < self.balance:
      self.balance -= money_w
      print(f"Actual balance: {self.balance}")
    else:
      print("ERROR: You dont have enough money to withdraw, try with less money")